#' Synthetic Oslo crime dataset for NearRepeatLite examples
#'
#' @description
#' A synthetic dataset of 500 crime events generated from the spatial and
#' temporal extent of real crime data in Oslo, Norway (2015--2019). Coordinates
#' are in UTM zone 32N (EPSG:25832). Dates cover the full five-year period.
#'
#' The dataset is entirely synthetic: coordinates and dates were drawn at
#' random within the Oslo bounding box and study period. A subset of
#' approximately 50 secondary events was injected within 200 m and 14 days of
#' randomly chosen seed events to produce mild near-repeat clustering, making
#' the Knox test output more informative as a demonstration.
#'
#' No real crime records are included. The underlying police register data
#' (STRASAK, Oslo 2015--2019) is not publicly available and is not distributed
#' with this package.
#'
#' @format A data frame with 500 rows and 3 variables:
#' \describe{
#'   \item{x}{Easting (UTM zone 32N, metres).}
#'   \item{y}{Northing (UTM zone 32N, metres).}
#'   \item{date}{Date of the event (\code{Date} class, YYYY-MM-DD).}
#' }
#'
#' @source Generated by \code{data-raw/generate_oslo_sim.R} using
#'   \code{set.seed(1519)}.
#'
#' @examples
#' data(oslo_sim)
#' head(oslo_sim)
#' range(oslo_sim$date)
"oslo_sim"
